### ISSUE TITLE
"/nowplaying" command

### ISSUE THREAD

**Issue by Uricorn** [mortenn/PlugUserspace#15]
"/nowplaying" To get some stats on the current playing song. (Amount of versions, when last played, by who, avg woots/grabs/mehs for when not skipped but no # of times played)

If you have a better idea for the command name, do tell since I don't like this one much.

**Comment by mortenn** [comment]
Basically, show the dj report?
I was planning on maybe adding more information like you describe here to that.

**Comment by Uricorn** [comment]
I do not want it to contain how many times it was played, or any other "total" stats, just some basic averages, last played, by whom, amount of versions and title.. stuff like that. 

It should be interesting but not really a "killer" feature. Also not a very high priority if it will take a lot of time to make this.

**Comment by Uricorn** [comment]
Not really important.
