### ISSUE TITLE
Don't display "v2" in op warnings

### ISSUE THREAD

**Issue by Uricorn** [mortenn/PlugUserspace#31]

**Comment by mortenn** [comment]
Care to clarify where this is?

**Comment by Uricorn** [comment]
Apparently in the playlist after checkall.

**Comment by mortenn** [comment]
isn't that just the number of linked songs?

**Comment by mortenn** [comment]
yes, that is the number of known alternates, not "v2".

**Comment by Uricorn** [comment]
I guess it's not clear
