### ISSUE TITLE
Mention sound volume not working?

### ISSUE THREAD

**Issue by Uricorn** [mortenn/PlugUserspace#32]
People are complaining that nyanpasu sound is too loud, it's already on 50% volume by default. I checked and lowering the volume to 1% didn't seem to have any effect.

**Comment by vitric** [comment]
https://github.com/mortenn/PlugUserspace/blob/1dadb0eba052cb62e20294d8ddde98e03e9f9581/soundbank.js#L182

Changing
`window.soundbank.values.sounds[i].volume`

to 
`window.soundbank.config.values.sounds[i].volume` 

should fix it
