### ISSUE TITLE
Support nightcore ban

### ISSUE THREAD

**Issue by Uricorn** [mortenn/PlugUserspace#33]

**Comment by mortenn** [comment]
This should be coordinated to happen when it actually goes into effect

**Comment by Uricorn** [comment]
I need a way to go through all songs we think are nightcore, and mass ban most of them.

I think anything that has nightcore in the title should be banned for nightcore, and then anything in the artist part should be went through manually. Just have to do a short sample for the title ones first.

**Comment by Uricorn** [comment]
I need a way to go through all songs we think are nightcore, and mass ban most of them.

I think anything that has nightcore in the title should be banned for nightcore, and then anything in the artist part should be went through manually. Just have to do a short sample for the title ones first.

**Comment by Uricorn** [comment]
Seems like there are only about 270 songs that have "nightcore" in the title.

Any of them that are not banned for another reason can be banned for "Nightcore".

I will now check authors.

**Comment by Uricorn** [comment]
Ok you can do the same with song authors with "nightcore" in them.

We can unban songs if we have a complaint.

New songs will be banned manually though, so less chance of a mistake.
