### ISSUE TITLE
Toggle Kouhai current song messages

### ISSUE THREAD

**Issue by Uricorn** [mortenn/PlugUserspace#9]
Toggles: off/on/only on linked songs/only on none linked songs

**Comment by Uricorn** [comment]
Currently you can toggle based on "unknown" but not on "not linked/linked".

**Comment by mortenn** [comment]
unknown is not linked

**Comment by Uricorn** [comment]
Can you please change the wording then so it will be aligned with the SenpaiScript wording.

In SenpaiScript "Unknown" means it has never played before. Which I guess could be a different interesting toggle at some point.

**Comment by mortenn** [comment]
kouhai already tells you when something is "unknown" in that it has become known by the time kouhai reports and will at that time say "this is the first time!"
